# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 585bc974244d0514f9330767382a271671ca5ce81afc71b43c55da7cf22b0964f8263b3145de142efea7511d2fd383b95704a8b09bd8070af71f4e58756c68ee

test:
  secret_key_base: f630364713532e50f6bbedbdcc50b989a8b60c6187975bc790b07de301cc5a64831c4b309915a5aed7b62e879860d2173fe6c63e6fc0e631987ad98c9992ce2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
